---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: alb-ingress-controller
  name: alb-ingress-controller
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: alb-ingress-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alb-ingress-controller
    spec:
      containers:
        - name: alb-ingress-controller
          args:
            - --ingress-class=alb
            - --cluster-name=mp-dban2-eks-cluster
          image: docker.io/amazon/aws-alb-ingress-controller:v1.18
      nodeSelector:
        eks.amazoneaws.com/nodegroup: ServiceNodeGroup
      serviceAccountName: alb-ingress-controller